version: '3'
services:
  backend:
    build: backend/
    command: gunicorn -b 0.0.0.0:80 app:app
    ports:
      - 5000:80
  frontend:
    build: ./authtest2/
    # command: http-server dist
    command: npm run dev
    ports:
      - 8001:8080
    depends_on:
      - backend